name: flutter_mb_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: "5.4.1"
  flutter_redux: "0.6.0"
  flutter_redux_dev_tools: ^0.4.0
  shared_preferences: 0.5.6+1
  equatable: ^0.6.1
  mockito: ^4.1.1
  http: 0.12.0+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

